<?php

namespace Babble\Models;

class Block extends BaseModel
{
    private $model;

    public function __construct(BaseModel $model, string $type)
    {
        $this->model = $model;
        parent::__construct($type);
    }


    protected function getDefinitionFile()
    {
        return '../models/blocks/' . $this->type . '.yaml';
    }

    public function getField(string $key)
    {
        return $this->fields[$key];
    }

    public function getType()
    {
        return parent::getType(); // TODO: Change the autogenerated stub
    }


    public function getCacheLocation(string $recordId)
    {
        $baseLocation = parent::getCacheLocation($recordId);
        return $baseLocation . $this->model->getType() . '/' . $recordId . '/' . $this->getType() . '/';
    }
}

