name = "Page"

[fields.title]
    name = "Title"
    type = "text"

[fields.image]
    name = "Header image"
    type = "image"

    [fields.image.options]
    width = 900
    height = 300

[fields.body]
    name = "Body"
    type = "text"

    [fields.body.options]
    multiline = true