name = "Blog post"

[options.admin]
list_display = ['title', 'is_draft', 'published']

[fields.title]
label = "Title"
type = "string"

[fields.published]
label = "Published at"
type = "datetime"

[fields.is_draft]
label = "Draft"
type = "boolean"

[fields.body]
label = "Body"
type = "textarea"