name = "Blog post"

[fields.title]
label = "Title"
type = "string"

[fields.published]
label = "Publish"
type = "datetime"

[fields.is_draft]
label = "Draft"
type = "boolean"

[fields.body]
label = "Body"
type = "textarea"