name = "Blog post"

[options.admin]
list_display = ['title', 'is_draft', 'published']

[fields.title]
name = "Title"
type = "string"

[fields.published]
name = "Published at"
type = "datetime"

[fields.is_draft]
name = "Draft"
type = "boolean"

[fields.body]
name = "Body"
type = "textarea"